Feature: support for shared downloads directory
laurent-clouet/sheepit-client pull request #295
Opened 2020-09-09 10:15 UTC by luguina

This feature is especially relevant for users with several clients running simultaneously within the same computer (computers running several GPUs or any combination of GPUs + CPUs) or multiple computers running in a network. The feature allows the user to specify a shared downloads directory via the new _-shared-downloads-dir_ client option. All the clients using that option will download the binaries and new scenes once and will share them across the clients.

**How it works?**
The first client downloading a binary or scene will save the file in the directory especified in _-shared-downloads-dir_. The rest of the clients using the same shared directory will wait until the file has been downloaded. Once the file has been downloaded, it will be ready for the rest of the clients.

This feature is especially relevant for users with metered/slow connections or multiple computers/multiple clients in the same machine that don't want to download the same binary/scene multiple times.

**IMPORTANT: All the clients intended to share the binaries and scenes must execute the client with the _same -shared-downloads-dir_ parameter.**

2020-09-09 17:05 UTC, laurent-clouet commented
Is it for project zip too ? or only blender binary zip ?

why not "-shared-zip" it's shorter ?

2020-09-09 21:35 UTC, luguina commented
> Is it for project zip too ? or only blender binary zip ?
Yes, it's for both binaries and projects.

> why not "-shared-zip" it's shorter ?
Done

2020-10-07 09:25 UTC, laurent-clouet commented
I did some tests today and I'm not sure it's working properly.
I've launched 2 clients with: "-shared-zip /tmp/55" on the same machine, both in CPU. I made sure the actual cache dir was autodetected.

I've some random error about 
07-10 11:19:08 (debug) Utils::unzipFileIntoDirectory(/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567.zip,/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567) exception net.lingala.zip4j.exception.ZipException: zip file does not exist stacktrace: net.lingala.zip4j.exception.ZipException: zip file does not exist

Or not founding the blender binary.

2020-10-08 06:41 UTC, Raimund58 requested changes

2020-10-08 06:41 UTC, Raimund58 commented on src/com/sheepit/client/Server.java
> +					}
This cleaning up seems not to work. I have still 18 hours worth of project files in my shared folder. (Sorry, couldn't test is for longer time yet)

2020-10-08 06:45 UTC, Raimund58 commented
A feature request from EyeForcz:
`I wished there would be a timeout setting. I got fast internet and 30min seems just to much for me`
This is also a good idea for people with super slow internet.

2020-10-08 07:06 UTC, Raimund58 commented on src/com/sheepit/client/Server.java
> +					}
I know why I have still project files left! The files were from a test run before I did let three clients run for 18 hours. 
So, if I would have cleaned the directory before starting the clients, everything would have been fine :D

2020-10-08 07:13 UTC, Raimund58 commented
Utils::unzipFileIntoDirectory(/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567.zip,/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567) exception net.lingala.zip4j.exception.ZipException: zip file does not exist stacktrace: net.lingala.zip4j.exception.ZipException: zip file does not exist
> 
> Or not founding the blender binary.

After 19 hours id did not happen to me. I searched all three log files from my clients...

2020-10-08 07:55 UTC, Raimund58 approved these changes
I would still love to see an option (cmd line argument) for the timeout because 30 minutes can be to short for people with slow internet and to long for people with fast internet.

2020-10-08 08:36 UTC, laurent-clouet commented
> I did some tests today and I'm not sure it's working properly.
> I've launched 2 clients with: "-shared-zip /tmp/55" on the same machine, both in CPU. I made sure the actual cache dir was autodetected.
> 
> I've some random error about
> 07-10 11:19:08 (debug) Utils::unzipFileIntoDirectory(/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567.zip,/tmp/farm_8240571721847630023/db26b54689516484633b7d4855fb1567) exception net.lingala.zip4j.exception.ZipException: zip file does not exist stacktrace: net.lingala.zip4j.exception.ZipException: zip file does not exist
> 
> Or not founding the blender binary.
> 
> (I'm available on discord for more tests)

It was happening because the shared zip directory was not created.
https://github.com/luguina/sheepit-client/commit/518e6b5d1473740538e2699b408770984995aee6 fix my issue.

2020-10-21 07:07 UTC, luguina commented
> I would still love to see an option (cmd line argument) for the timeout because 30 minutes can be to short for people with slow internet and to long for people with fast internet.

I understand the reason for slow connections, @Raimund58 but not sure about people with fast ones. If you have a fast connection, the client that is downloading the file will finish fast and the rest of the clients will immediately extract and start rendering the project. They don't need to wait the full 30 minutes. It's just a timeout in case the main client gets frozen with the initial download.

Interested anyway in what should be the lower limit in your opinion (upper limit should not be more than, let's say 1h30 to allow the computer downloading and then rendering the frame before the 2h hard limit, but interested in your thoughts).

2020-10-21 07:25 UTC, Raimund58 commented
> If you have a fast connection, the client that is downloading the file will finish fast and the rest of the clients will immediately extract and start rendering the project. They don't need to wait the full 30 minutes.

Understood. 

> Interested to know as well what should be the lower limit in your opinion (upper limit should not be more than, let's say 1h30 to allow the computer downloading and then rendering the frame before the 2h hard limit, but interested in your thoughts).

I'm not sure what would be the best. Maybe a cmd argument to set the timeout? I just tried to look from another perspective :)

2020-10-21 11:02 UTC, laurent-clouet commented on src/com/sheepit/client/Server.java
> +					}
cleaning works now.

2020-10-21 11:03 UTC, merged